version: "3.8"
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    hostname: rabbitmqhost
    volumes:
      - rabbitmq_data_chat:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fastapichat
      POSTGRES_PASSWORD: password

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/val/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  app:
    container_name: app
    restart: always
    build: ./app
    command: bash -c "alembic upgrade head && python main.py"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

volumes:
  rabbitmq_data_chat:
  pgadmin_data:
  db_data:
