"""init revision

Revision ID: 0e6bfb09897b
Revises: 
Create Date: 2022-04-28 07:50:41.750055

"""
from alembic import op
import sqlalchemy as sa
from data.hash import hash_password


# revision identifiers, used by Alembic.
revision = '0e6bfb09897b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        users_table,
        [
            {
                "username": "admin",
                "password": hash_password("admin")
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
