"""init revision

Revision ID: 9648839bcf80
Revises: 
Create Date: 2022-05-03 11:25:12.040620

"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from data.hash import hash_password

# revision identifiers, used by Alembic.
revision = '9648839bcf80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
                                  sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
                                  sa.Column('username', sa.String(length=25), nullable=True),
                                  sa.Column('password', sa.Text(), nullable=True),
                                  sa.PrimaryKeyConstraint('user_id'),
                                  sa.UniqueConstraint('username')
                                  )
    # ### end Alembic commands ###

    op.bulk_insert(
        users_table,
        [
            {
                "user_id": uuid.UUID("00000000-0000-4000-a000-000000000000"),
                "username": "admin",
                "password": hash_password("admin")
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
